/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.UUID;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Attachment model.
 */
public class Attachment {
    /**
     * The id property.
     */
    @JsonProperty(value = "id", required = true)
    private UUID id;

    /**
     * The contentType property.
     */
    @JsonProperty(value = "contentType")
    private String contentType;

    /**
     * The fileName property.
     */
    @JsonProperty(value = "fileName")
    private String fileName;

    /**
     * The contentId property.
     */
    @JsonProperty(value = "contentId")
    private String contentId;

    /**
     * The length property.
     */
    @JsonProperty(value = "length")
    private Long length;

    /**
     * The creationDate property.
     */
    @JsonProperty(value = "creationDate")
    private DateTime creationDate;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public UUID id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Attachment object itself.
     */
    public Attachment withId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get the contentType value.
     *
     * @return the contentType value
     */
    public String contentType() {
        return this.contentType;
    }

    /**
     * Set the contentType value.
     *
     * @param contentType the contentType value to set
     * @return the Attachment object itself.
     */
    public Attachment withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }

    /**
     * Get the fileName value.
     *
     * @return the fileName value
     */
    public String fileName() {
        return this.fileName;
    }

    /**
     * Set the fileName value.
     *
     * @param fileName the fileName value to set
     * @return the Attachment object itself.
     */
    public Attachment withFileName(String fileName) {
        this.fileName = fileName;
        return this;
    }

    /**
     * Get the contentId value.
     *
     * @return the contentId value
     */
    public String contentId() {
        return this.contentId;
    }

    /**
     * Set the contentId value.
     *
     * @param contentId the contentId value to set
     * @return the Attachment object itself.
     */
    public Attachment withContentId(String contentId) {
        this.contentId = contentId;
        return this;
    }

    /**
     * Get the length value.
     *
     * @return the length value
     */
    public Long length() {
        return this.length;
    }

    /**
     * Set the length value.
     *
     * @param length the length value to set
     * @return the Attachment object itself.
     */
    public Attachment withLength(Long length) {
        this.length = length;
        return this;
    }

    /**
     * Get the creationDate value.
     *
     * @return the creationDate value
     */
    public DateTime creationDate() {
        return this.creationDate;
    }

    /**
     * Set the creationDate value.
     *
     * @param creationDate the creationDate value to set
     * @return the Attachment object itself.
     */
    public Attachment withCreationDate(DateTime creationDate) {
        this.creationDate = creationDate;
        return this;
    }

}
