/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The EmailData model.
 */
public class EmailData {
    /**
     * The links property.
     */
    @JsonProperty(value = "links")
    private List<Link> links;

    /**
     * The images property.
     */
    @JsonProperty(value = "images")
    private List<Image> images;

    /**
     * The body property.
     */
    @JsonProperty(value = "body")
    private String body;

    /**
     * Get the links value.
     *
     * @return the links value
     */
    public List<Link> links() {
        return this.links;
    }

    /**
     * Set the links value.
     *
     * @param links the links value to set
     * @return the EmailData object itself.
     */
    public EmailData withLinks(List<Link> links) {
        this.links = links;
        return this;
    }

    /**
     * Get the images value.
     *
     * @return the images value
     */
    public List<Image> images() {
        return this.images;
    }

    /**
     * Set the images value.
     *
     * @param images the images value to set
     * @return the EmailData object itself.
     */
    public EmailData withImages(List<Image> images) {
        this.images = images;
        return this;
    }

    /**
     * Get the body value.
     *
     * @return the body value
     */
    public String body() {
        return this.body;
    }

    /**
     * Set the body value.
     *
     * @param body the body value to set
     * @return the EmailData object itself.
     */
    public EmailData withBody(String body) {
        this.body = body;
        return this;
    }

}
