/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Image model.
 */
public class Image {
    /**
     * The src property.
     */
    @JsonProperty(value = "src")
    private String src;

    /**
     * The alt property.
     */
    @JsonProperty(value = "alt")
    private String alt;

    /**
     * Get the src value.
     *
     * @return the src value
     */
    public String src() {
        return this.src;
    }

    /**
     * Set the src value.
     *
     * @param src the src value to set
     * @return the Image object itself.
     */
    public Image withSrc(String src) {
        this.src = src;
        return this;
    }

    /**
     * Get the alt value.
     *
     * @return the alt value
     */
    public String alt() {
        return this.alt;
    }

    /**
     * Set the alt value.
     *
     * @param alt the alt value to set
     * @return the Image object itself.
     */
    public Image withAlt(String alt) {
        this.alt = alt;
        return this;
    }

}
