/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Link model.
 */
public class Link {
    /**
     * The href property.
     */
    @JsonProperty(value = "href")
    private String href;

    /**
     * The text property.
     */
    @JsonProperty(value = "text")
    private String text;

    /**
     * Get the href value.
     *
     * @return the href value
     */
    public String href() {
        return this.href;
    }

    /**
     * Set the href value.
     *
     * @param href the href value to set
     * @return the Link object itself.
     */
    public Link withHref(String href) {
        this.href = href;
        return this;
    }

    /**
     * Get the text value.
     *
     * @return the text value
     */
    public String text() {
        return this.text;
    }

    /**
     * Set the text value.
     *
     * @param text the text value to set
     * @return the Link object itself.
     */
    public Link withText(String text) {
        this.text = text;
        return this;
    }

}
