/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Type serialized down the wire.
 */
public class MessageListResult {
    /**
     * The items property.
     */
    @JsonProperty(value = "items")
    private List<MessageSummary> items;

    /**
     * Get the items value.
     *
     * @return the items value
     */
    public List<MessageSummary> items() {
        return this.items;
    }

    /**
     * Set the items value.
     *
     * @param items the items value to set
     * @return the MessageListResult object itself.
     */
    public MessageListResult withItems(List<MessageSummary> items) {
        this.items = items;
        return this;
    }

}
