/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The MessageHeader model.
 */
public class MessageHeader {
    /**
     * The field property.
     */
    @JsonProperty(value = "field")
    private String field;

    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get the field value.
     *
     * @return the field value
     */
    public String field() {
        return this.field;
    }

    /**
     * Set the field value.
     *
     * @param field the field value to set
     * @return the MessageHeader object itself.
     */
    public MessageHeader withField(String field) {
        this.field = field;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the MessageHeader object itself.
     */
    public MessageHeader withValue(String value) {
        this.value = value;
        return this;
    }

}
