/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.Map;
import java.util.List;
import org.joda.time.DateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Message model.
 */
public class Message {
    /**
     * The html property.
     */
    @JsonProperty(value = "html")
    private EmailData html;

    /**
     * The text property.
     */
    @JsonProperty(value = "text")
    private EmailData text;

    /**
     * The headers property.
     */
    @JsonProperty(value = "headers")
    private Map<String, Object> headers;

    /**
     * The subject property.
     */
    @JsonProperty(value = "subject")
    private String subject;

    /**
     * The from property.
     */
    @JsonProperty(value = "from")
    private List<EmailAddress> from;

    /**
     * The to property.
     */
    @JsonProperty(value = "to")
    private List<EmailAddress> to;

    /**
     * The attachments property.
     */
    @JsonProperty(value = "attachments")
    private List<Attachment> attachments;

    /**
     * The received property.
     */
    @JsonProperty(value = "received", required = true)
    private DateTime received;

    /**
     * The senderhost property.
     */
    @JsonProperty(value = "senderhost")
    private String senderhost;

    /**
     * The server property.
     */
    @JsonProperty(value = "server")
    private String server;

    /**
     * The id property.
     */
    @JsonProperty(value = "id", required = true)
    private UUID id;

    /**
     * Get the html value.
     *
     * @return the html value
     */
    public EmailData html() {
        return this.html;
    }

    /**
     * Set the html value.
     *
     * @param html the html value to set
     * @return the Message object itself.
     */
    public Message withHtml(EmailData html) {
        this.html = html;
        return this;
    }

    /**
     * Get the text value.
     *
     * @return the text value
     */
    public EmailData text() {
        return this.text;
    }

    /**
     * Set the text value.
     *
     * @param text the text value to set
     * @return the Message object itself.
     */
    public Message withText(EmailData text) {
        this.text = text;
        return this;
    }

    /**
     * Get the headers value.
     *
     * @return the headers value
     */
    public Map<String, Object> headers() {
        return this.headers;
    }

    /**
     * Set the headers value.
     *
     * @param headers the headers value to set
     * @return the Message object itself.
     */
    public Message withHeaders(Map<String, Object> headers) {
        this.headers = headers;
        return this;
    }

    /**
     * Get the subject value.
     *
     * @return the subject value
     */
    public String subject() {
        return this.subject;
    }

    /**
     * Set the subject value.
     *
     * @param subject the subject value to set
     * @return the Message object itself.
     */
    public Message withSubject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * Get the from value.
     *
     * @return the from value
     */
    public List<EmailAddress> from() {
        return this.from;
    }

    /**
     * Set the from value.
     *
     * @param from the from value to set
     * @return the Message object itself.
     */
    public Message withFrom(List<EmailAddress> from) {
        this.from = from;
        return this;
    }

    /**
     * Get the to value.
     *
     * @return the to value
     */
    public List<EmailAddress> to() {
        return this.to;
    }

    /**
     * Set the to value.
     *
     * @param to the to value to set
     * @return the Message object itself.
     */
    public Message withTo(List<EmailAddress> to) {
        this.to = to;
        return this;
    }

    /**
     * Get the attachments value.
     *
     * @return the attachments value
     */
    public List<Attachment> attachments() {
        return this.attachments;
    }

    /**
     * Set the attachments value.
     *
     * @param attachments the attachments value to set
     * @return the Message object itself.
     */
    public Message withAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
        return this;
    }

    /**
     * Get the received value.
     *
     * @return the received value
     */
    public DateTime received() {
        return this.received;
    }

    /**
     * Set the received value.
     *
     * @param received the received value to set
     * @return the Message object itself.
     */
    public Message withReceived(DateTime received) {
        this.received = received;
        return this;
    }

    /**
     * Get the senderhost value.
     *
     * @return the senderhost value
     */
    public String senderhost() {
        return this.senderhost;
    }

    /**
     * Set the senderhost value.
     *
     * @param senderhost the senderhost value to set
     * @return the Message object itself.
     */
    public Message withSenderhost(String senderhost) {
        this.senderhost = senderhost;
        return this;
    }

    /**
     * Get the server value.
     *
     * @return the server value
     */
    public String server() {
        return this.server;
    }

    /**
     * Set the server value.
     *
     * @param server the server value to set
     * @return the Message object itself.
     */
    public Message withServer(String server) {
        this.server = server;
        return this;
    }

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public UUID id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Message object itself.
     */
    public Message withId(UUID id) {
        this.id = id;
        return this;
    }

}
