/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The MessageAddress model.
 */
public class MessageAddress {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The email property.
     */
    @JsonProperty(value = "email")
    private String email;

    /**
     * The phone property.
     */
    @JsonProperty(value = "phone")
    private String phone;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the MessageAddress object itself.
     */
    public MessageAddress withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the email value.
     *
     * @return the email value
     */
    public String email() {
        return this.email;
    }

    /**
     * Set the email value.
     *
     * @param email the email value to set
     * @return the MessageAddress object itself.
     */
    public MessageAddress withEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Get the phone value.
     *
     * @return the phone value
     */
    public String phone() {
        return this.phone;
    }

    /**
     * Set the phone value.
     *
     * @param phone the phone value to set
     * @return the MessageAddress object itself.
     */
    public MessageAddress withPhone(String phone) {
        this.phone = phone;
        return this;
    }

}
