/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Metadata model.
 */
public class Metadata {
    /**
     * The headers property.
     */
    @JsonProperty(value = "headers")
    private List<MessageHeader> headers;

    /**
     * Get the headers value.
     *
     * @return the headers value
     */
    public List<MessageHeader> headers() {
        return this.headers;
    }

    /**
     * Set the headers value.
     *
     * @param headers the headers value to set
     * @return the Metadata object itself.
     */
    public Metadata withHeaders(List<MessageHeader> headers) {
        this.headers = headers;
        return this;
    }

}
