/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ServerCreateOptions model.
 */
public class ServerCreateOptions {
    /**
     * A name used to identify the server.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ServerCreateOptions object itself.
     */
    public ServerCreateOptions withName(String name) {
        this.name = name;
        return this;
    }

}
