/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Server model.
 */
public class Server {
    /**
     * Unique identifier for the server.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * The password used for SMTP authentication.
     */
    @JsonProperty(value = "password")
    private String password;

    /**
     * A name used to identify the server.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The users property.
     */
    @JsonProperty(value = "users")
    private List<UUID> users;

    /**
     * The current count of emails held within the server.
     */
    @JsonProperty(value = "emails")
    private Integer emails;

    /**
     * The forwardingRules property.
     */
    @JsonProperty(value = "forwardingRules")
    private List<ForwardingRule> forwardingRules;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the Server object itself.
     */
    public Server withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the password value.
     *
     * @return the password value
     */
    public String password() {
        return this.password;
    }

    /**
     * Set the password value.
     *
     * @param password the password value to set
     * @return the Server object itself.
     */
    public Server withPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Server object itself.
     */
    public Server withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the users value.
     *
     * @return the users value
     */
    public List<UUID> users() {
        return this.users;
    }

    /**
     * Set the users value.
     *
     * @param users the users value to set
     * @return the Server object itself.
     */
    public Server withUsers(List<UUID> users) {
        this.users = users;
        return this;
    }

    /**
     * Get the emails value.
     *
     * @return the emails value
     */
    public Integer emails() {
        return this.emails;
    }

    /**
     * Set the emails value.
     *
     * @param emails the emails value to set
     * @return the Server object itself.
     */
    public Server withEmails(Integer emails) {
        this.emails = emails;
        return this;
    }

    /**
     * Get the forwardingRules value.
     *
     * @return the forwardingRules value
     */
    public List<ForwardingRule> forwardingRules() {
        return this.forwardingRules;
    }

    /**
     * Set the forwardingRules value.
     *
     * @param forwardingRules the forwardingRules value to set
     * @return the Server object itself.
     */
    public Server withForwardingRules(List<ForwardingRule> forwardingRules) {
        this.forwardingRules = forwardingRules;
        return this;
    }

}
