/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SpamAssassinRule model.
 */
public class SpamAssassinRule {
    /**
     * The score property.
     */
    @JsonProperty(value = "score")
    private Double score;

    /**
     * The rule property.
     */
    @JsonProperty(value = "rule")
    private String rule;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * Get the score value.
     *
     * @return the score value
     */
    public Double score() {
        return this.score;
    }

    /**
     * Set the score value.
     *
     * @param score the score value to set
     * @return the SpamAssassinRule object itself.
     */
    public SpamAssassinRule withScore(Double score) {
        this.score = score;
        return this;
    }

    /**
     * Get the rule value.
     *
     * @return the rule value
     */
    public String rule() {
        return this.rule;
    }

    /**
     * Set the rule value.
     *
     * @param rule the rule value to set
     * @return the SpamAssassinRule object itself.
     */
    public SpamAssassinRule withRule(String rule) {
        this.rule = rule;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the SpamAssassinRule object itself.
     */
    public SpamAssassinRule withDescription(String description) {
        this.description = description;
        return this;
    }

}
