/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.models;

import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The SpamCheckResult model.
 */
public class SpamCheckResult {
    /**
     * The spamAssassin property.
     */
    @JsonProperty(value = "spamAssassin")
    private List<SpamAssassinRule> spamAssassin;

    /**
     * The emailId property.
     */
    @JsonProperty(value = "emailId")
    private UUID emailId;

    /**
     * The accountId property.
     */
    @JsonProperty(value = "accountId")
    private UUID accountId;

    /**
     * The score property.
     */
    @JsonProperty(value = "score")
    private Double score;

    /**
     * Get the spamAssassin value.
     *
     * @return the spamAssassin value
     */
    public List<SpamAssassinRule> spamAssassin() {
        return this.spamAssassin;
    }

    /**
     * Set the spamAssassin value.
     *
     * @param spamAssassin the spamAssassin value to set
     * @return the SpamCheckResult object itself.
     */
    public SpamCheckResult withSpamAssassin(List<SpamAssassinRule> spamAssassin) {
        this.spamAssassin = spamAssassin;
        return this;
    }

    /**
     * Get the emailId value.
     *
     * @return the emailId value
     */
    public UUID emailId() {
        return this.emailId;
    }

    /**
     * Set the emailId value.
     *
     * @param emailId the emailId value to set
     * @return the SpamCheckResult object itself.
     */
    public SpamCheckResult withEmailId(UUID emailId) {
        this.emailId = emailId;
        return this;
    }

    /**
     * Get the accountId value.
     *
     * @return the accountId value
     */
    public UUID accountId() {
        return this.accountId;
    }

    /**
     * Set the accountId value.
     *
     * @param accountId the accountId value to set
     * @return the SpamCheckResult object itself.
     */
    public SpamCheckResult withAccountId(UUID accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Get the score value.
     *
     * @return the score value
     */
    public Double score() {
        return this.score;
    }

    /**
     * Set the score value.
     *
     * @param score the score value to set
     * @return the SpamCheckResult object itself.
     */
    public SpamCheckResult withScore(Double score) {
        this.score = score;
        return this;
    }

}
