/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur.implementation;

import com.mailosaur.MailosaurBaseClient;
import com.mailosaur.Analysis;
import com.mailosaur.Files;
import com.mailosaur.Messages;
import com.mailosaur.Servers;
import com.microsoft.rest.ServiceClient;
import com.microsoft.rest.RestClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

/**
 * Initializes a new instance of the MailosaurBaseClient class.
 */
public class MailosaurBaseClientImpl extends ServiceClient implements MailosaurBaseClient {

    /**
     * The Analysis object to access its operations.
     */
    private Analysis analysis;

    /**
     * Gets the Analysis object to access its operations.
     * @return the Analysis object.
     */
    public Analysis analysis() {
        return this.analysis;
    }

    /**
     * The Files object to access its operations.
     */
    private Files files;

    /**
     * Gets the Files object to access its operations.
     * @return the Files object.
     */
    public Files files() {
        return this.files;
    }

    /**
     * The Messages object to access its operations.
     */
    private Messages messages;

    /**
     * Gets the Messages object to access its operations.
     * @return the Messages object.
     */
    public Messages messages() {
        return this.messages;
    }

    /**
     * The Servers object to access its operations.
     */
    private Servers servers;

    /**
     * Gets the Servers object to access its operations.
     * @return the Servers object.
     */
    public Servers servers() {
        return this.servers;
    }

    /**
     * Initializes an instance of MailosaurBaseClient client.
     */
    public MailosaurBaseClientImpl() {
        this("https://mailosaur.com");
    }

    /**
     * Initializes an instance of MailosaurBaseClient client.
     *
     * @param baseUrl the base URL of the host
     */
    public MailosaurBaseClientImpl(String baseUrl) {
        super(baseUrl);
        initialize();
    }

    /**
     * Initializes an instance of MailosaurBaseClient client.
     *
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public MailosaurBaseClientImpl(OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        this("https://mailosaur.com", clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of MailosaurBaseClient client.
     *
     * @param baseUrl the base URL of the host
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public MailosaurBaseClientImpl(String baseUrl, OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        super(baseUrl, clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of MailosaurBaseClient client.
     *
     * @param restClient the REST client containing pre-configured settings
     */
    public MailosaurBaseClientImpl(RestClient restClient) {
        super(restClient);
        initialize();
    }

    private void initialize() {
        this.analysis = new AnalysisImpl(retrofit(), this);
        this.files = new FilesImpl(retrofit(), this);
        this.messages = new MessagesImpl(retrofit(), this);
        this.servers = new ServersImpl(retrofit(), this);
    }
}
