/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur;

import com.mailosaur.models.Email;
import com.mailosaur.MailosaurException;
import com.mailosaur.models.SearchCriteria;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import java.io.IOException;
import java.util.List;
import java.util.UUID;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in Emails.
 */
public interface Emails {
    /**
     * Retrieve an email.
     * Retrieves the detail for a single email. Simply supply the unique identifier for the required email.
     *
     * @param id The identifier of the email to be retrieved.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the Email object if successful.
     */
    Email get(UUID id);

    /**
     * Retrieve an email.
     * Retrieves the detail for a single email. Simply supply the unique identifier for the required email.
     *
     * @param id The identifier of the email to be retrieved.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Email> getAsync(UUID id, final ServiceCallback<Email> serviceCallback);

    /**
     * Retrieve an email.
     * Retrieves the detail for a single email. Simply supply the unique identifier for the required email.
     *
     * @param id The identifier of the email to be retrieved.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Email object
     */
    Observable<Email> getAsync(UUID id);

    /**
     * Retrieve an email.
     * Retrieves the detail for a single email. Simply supply the unique identifier for the required email.
     *
     * @param id The identifier of the email to be retrieved.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Email object
     */
    Observable<ServiceResponse<Email>> getWithServiceResponseAsync(UUID id);

    /**
     * Delete an email.
     * Permanently deletes an email. This operation cannot be undone. Also deletes any attachments related to the email.
     *
     * @param id The identifier of the email to be deleted.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    void delete(UUID id);

    /**
     * Delete an email.
     * Permanently deletes an email. This operation cannot be undone. Also deletes any attachments related to the email.
     *
     * @param id The identifier of the email to be deleted.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Void> deleteAsync(UUID id, final ServiceCallback<Void> serviceCallback);

    /**
     * Delete an email.
     * Permanently deletes an email. This operation cannot be undone. Also deletes any attachments related to the email.
     *
     * @param id The identifier of the email to be deleted.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<Void> deleteAsync(UUID id);

    /**
     * Delete an email.
     * Permanently deletes an email. This operation cannot be undone. Also deletes any attachments related to the email.
     *
     * @param id The identifier of the email to be deleted.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<ServiceResponse<Void>> deleteWithServiceResponseAsync(UUID id);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the List&lt;Email&gt; object if successful.
     */
    List<Email> list(String server);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<List<Email>> listAsync(String server, final ServiceCallback<List<Email>> serviceCallback);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<List<Email>> listAsync(String server);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<ServiceResponse<List<Email>>> listWithServiceResponseAsync(String server);
    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the List&lt;Email&gt; object if successful.
     */
    List<Email> list(String server, Integer pagenumber, Integer itemsperpage);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<List<Email>> listAsync(String server, Integer pagenumber, Integer itemsperpage, final ServiceCallback<List<Email>> serviceCallback);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<List<Email>> listAsync(String server, Integer pagenumber, Integer itemsperpage);

    /**
     * List all emails.
     * Returns a list of your emails. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<ServiceResponse<List<Email>>> listWithServiceResponseAsync(String server, Integer pagenumber, Integer itemsperpage);

    /**
     * Delete all emails.
     * Permanently deletes all emails held by the specified server. This operation cannot be undone. Also deletes any attachments related to each email.
     *
     * @param server The identifier of the server to be emptied.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     */
    void deleteAll(String server);

    /**
     * Delete all emails.
     * Permanently deletes all emails held by the specified server. This operation cannot be undone. Also deletes any attachments related to each email.
     *
     * @param server The identifier of the server to be emptied.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Void> deleteAllAsync(String server, final ServiceCallback<Void> serviceCallback);

    /**
     * Delete all emails.
     * Permanently deletes all emails held by the specified server. This operation cannot be undone. Also deletes any attachments related to each email.
     *
     * @param server The identifier of the server to be emptied.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<Void> deleteAllAsync(String server);

    /**
     * Delete all emails.
     * Permanently deletes all emails held by the specified server. This operation cannot be undone. Also deletes any attachments related to each email.
     *
     * @param server The identifier of the server to be emptied.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceResponse} object if successful.
     */
    Observable<ServiceResponse<Void>> deleteAllWithServiceResponseAsync(String server);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the List&lt;Email&gt; object if successful.
     */
    List<Email> search(String server, SearchCriteria criteria);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<List<Email>> searchAsync(String server, SearchCriteria criteria, final ServiceCallback<List<Email>> serviceCallback);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<List<Email>> searchAsync(String server, SearchCriteria criteria);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<ServiceResponse<List<Email>>> searchWithServiceResponseAsync(String server, SearchCriteria criteria);
    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the List&lt;Email&gt; object if successful.
     */
    List<Email> search(String server, SearchCriteria criteria, Integer pagenumber, Integer itemsperpage);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<List<Email>> searchAsync(String server, SearchCriteria criteria, Integer pagenumber, Integer itemsperpage, final ServiceCallback<List<Email>> serviceCallback);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<List<Email>> searchAsync(String server, SearchCriteria criteria, Integer pagenumber, Integer itemsperpage);

    /**
     * Search for emails.
     * Returns a list of emails matching the specified search criteria. The emails are returned sorted by received date, with the most recently-received emails appearing first.
     *
     * @param server The identifier of the server hosting the emails.
     * @param criteria The search criteria to match results against.
     * @param pagenumber Used in conjunction with `itemsperpage` to support pagination.
     * @param itemsperpage A limit on the number of results to be returned. Can be set between 1 and 1000 items, the default is 50.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the List&lt;Email&gt; object
     */
    Observable<ServiceResponse<List<Email>>> searchWithServiceResponseAsync(String server, SearchCriteria criteria, Integer pagenumber, Integer itemsperpage);

    /**
     * Wait for a specific email.
     * Returns as soon as an email matching the specified search criteria is found.
     *
     * @param server The identifier of the server hosting the email.
     * @param criteria The search criteria to use in order to find a match.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws MailosaurException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the Email object if successful.
     */
    Email waitFor(String server, SearchCriteria criteria);

    /**
     * Wait for a specific email.
     * Returns as soon as an email matching the specified search criteria is found.
     *
     * @param server The identifier of the server hosting the email.
     * @param criteria The search criteria to use in order to find a match.
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    ServiceFuture<Email> waitForAsync(String server, SearchCriteria criteria, final ServiceCallback<Email> serviceCallback);

    /**
     * Wait for a specific email.
     * Returns as soon as an email matching the specified search criteria is found.
     *
     * @param server The identifier of the server hosting the email.
     * @param criteria The search criteria to use in order to find a match.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Email object
     */
    Observable<Email> waitForAsync(String server, SearchCriteria criteria);

    /**
     * Wait for a specific email.
     * Returns as soon as an email matching the specified search criteria is found.
     *
     * @param server The identifier of the server hosting the email.
     * @param criteria The search criteria to use in order to find a match.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the Email object
     */
    Observable<ServiceResponse<Email>> waitForWithServiceResponseAsync(String server, SearchCriteria criteria);

}
