/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur;

import com.mailosaur.models.MailosaurError;

/**
 * Exception thrown for an invalid response with MailosaurError information.
 */
public class MailosaurException extends Exception {
	public MailosaurException(String message, Exception ex) {
		
	}
	
    public MailosaurError mailosaurError() {
        return null;
    }
}

