/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.mailosaur;

import com.microsoft.rest.RestClient;

/**
 * The interface for MailosaurBaseClient class.
 */
public interface MailosaurBaseClient {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://mailosaur.com";

    /**
     * Gets the Analysis object to access its operations.
     * @return the Analysis object.
     */
    Analysis analysis();

    /**
     * Gets the Files object to access its operations.
     * @return the Files object.
     */
    Files files();

    /**
     * Gets the Messages object to access its operations.
     * @return the Messages object.
     */
    Messages messages();

    /**
     * Gets the Servers object to access its operations.
     * @return the Servers object.
     */
    Servers servers();

}
